create table if not exists users (
                                     username varchar(50) not null primary key,
    password varchar(100) not null,
    enabled boolean not null
    );

create table if not exists authorities (
                                           username varchar(50) not null,
    authority varchar(50) not null,
    constraint fk_authorities_users foreign key(username) references users(username)
    );

create unique index if not exists ix_auth_username on authorities (username, authority);

create table if not exists products (
                                        id bigint generated by default as identity primary key,
                                        name varchar(100) not null,
    price int not null,
    owner_username varchar(50) not null,
    created_at timestamp default current_timestamp
    );